plugins: 
  - babel
  - react

extends:
  - airbnb-base
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true

rules:
  quotes: ["error", "double"]
  linebreak-style: "off"
  import/prefer-default-export: "off" 